name: 02-sync-history

on:
  workflow_run:
    workflows: ["01-update-prices"]
    types: [completed]
  workflow_dispatch: {}

concurrency:
  group: nightly-pipeline
  cancel-in-progress: false

jobs:
  run:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Sync ~90d historical
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
        run: python sync_historical_90d.py
