name: 05-update-nasdaq

on:
  workflow_run:
    workflows: ["04-forecast"]
    types: [completed]
  workflow_dispatch: {}

concurrency:
  group: nightly-pipeline
  cancel-in-progress: false

jobs:
  run:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install core deps
        run: |
          pip install python-dotenv
      - name: Update Nasdaq daily snapshot
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
        run: python .github/update_nasdaq_snapshot.py
