name: nightly-forecasts

on:

  workflow_dispatch: {}        # تشغيل يدوي من تبويب Actions

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (from requirements.txt)
        run: pip install -r requirements.txt

      # لو سكربت التوقعات في مجلد غيّر المسار بالسطر التالي
      - name: Run forecast script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
        run: python forecast_generate_tracked_symbols_v6i_1day_silent.py
